name: PR Title Check

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "$(echo "$PR_TITLE" | grep -E '^(fix|feat|tech|docs|bump|style|refactor|chore|perf|test|revert|breaking)(\([^)]+\))?:')" ]]; then
            echo "Error: Pull request title must start with one of the following keywords: fix, feat, tech, docs, bump, style, refactor, chore, perf, test, breaking or revert. Optionally, it can include a scope in parentheses followed by a colon (e.g., 'feat(scope):')."
            exit 1
          fi
